mcl_3dl:
  # Frame
  map_frame: "map"
  robot_frame: "base_link"
  odom_frame: "odom"
  floor_frame: "floor"
  # Downsampling the Map
  map_downsample_x: 0.2 #0.05
  map_downsample_y: 0.2 #0.05
  map_downsample_z: 0.2 #0.05
  # Downsampling the Cloud
  downsample_x: 0.1 #0.1 
  downsample_y: 0.1 #0.1
  downsample_z: 0.1 #0.1
  # Downsampling the update map
  update_downsample_x: 0.3
  update_downsample_y: 0.3
  update_downsample_z: 0.3
  map_update_interval_interval: 2.0
  # Weight - Global Localization
  dist_weight_x: 1.0
  dist_weight_y: 1.0
  dist_weight_z: 5.0
  global_localization_grid_lin: 0.3
  global_localization_grid_ang: 0.524
  # Particles No.
  num_particles: 400 #400 #256
  # Redistribute particles after movement
  resample_var_x: 0.05 #0.05 #[m]
  resample_var_y: 0.05 #0.05
  resample_var_z: 0.05 #0.05
  resample_var_roll: 0.01 #0.01 #0.05 #[rad]
  resample_var_pitch: 0.01 #0.01 #0.05
  resample_var_yaw: 0.1 #0.02 #0.1 #14Nov2019
  # Redistribute particles in Normal Distribution randomly
  expansion_var_x: 0.1 #0.2  #[m]
  expansion_var_y: 0.1 #0.2
  expansion_var_z: 0.05 #0.1 #0.2
  expansion_var_roll: 0.01 #[rad]
  expansion_var_pitch: 0.01 #0.05
  expansion_var_yaw: 0.02 #0.01 #0.05
  match_ratio_thresh: 0.0
  # Odom propagating particle distribution
  odom_err_lin_lin: 0.1 #0.01 #0.05
  odom_err_lin_ang: 0.01 #0.05 
  odom_err_ang_lin: 0.05 #0.01 #0.05 
  odom_err_ang_ang: 0.01 #0.05 
  odom_err_integ_lin_tc: 1.0 #0.1 #10.0
  odom_err_integ_lin_sigma: 10.0 #1.0 #100.0
  odom_err_integ_ang_tc: 0.0 #0.1 #10.0
  odom_err_integ_ang_sigma: 0.0 #1.0 #100.0
  # Initial
  init_x: 0.35 #2.13
  init_y: 2.35 #2.69
  init_z: 0.1 #-0.35
  init_roll: 0.0
  init_pitch: 0.0
  init_yaw: -1.570796
  init_var_x: 1.0 #2.0
  init_var_y: 1.0 #2.0
  init_var_z: 0.5
  init_var_roll: 0.1
  init_var_pitch: 0.1
  init_var_yaw: 0.5
  # Others
  lpf_step: 1.0 #16.0
  acc_lpf_step: 128.0
  acc_var: 0.78539816339 # pi/4
  jump_dist: 1.0
  jump_ang: 1.57
  fix_dist: 0.2
  fix_ang: 0.1
  bias_var_dist: 100.0
  bias_var_ang: 0.1
  skip_measure: 1
  accum_cloud: 1
  match_output_dist: 0.2
  unmatch_output_dist: 0.5
  match_output_interval_interval: 0.2
  # TF
  tf_tolerance: 0.05 #[sec]
  publish_tf: true
  output_pcd: false
  map_chunk: 20.0
  # Likelihood
  likelihood:
    match_dist_min: 0.2 #0.3 #0.2 #[m]
    match_dist_flat: 0.05  #[m]
    match_weight: 5.0 #4.0 #5.0
    num_points: 96
    num_points_global: 8
    clip_near: 0.5 #[m]
    clip_far: 120.0 #10.0
    clip_z_min: -0.3 #-2.0 #[m]
    clip_z_max: 15.0 #2.0
  # Beam
#  beam:
#    num_points: 3
#    num_points_global: 0
#    clip_near: 0.5 #[m]
#    clip_far: 100.0 #4.0
#    clip_z_min: -2.0 #[m]
#    clip_z_max: 10.0
#    beam_likelihood: 0.2
#    ang_total_ref: 0.52359877559 #[rad]




obj_to_pointcloud:
  frame_id: "map"
  points_per_meter_sq: 1200.0
  downsample_grid: 0.1
pcd_to_pointcloud:
  frame_id: "map"
  latch: true
track_odometry:
  z_filter: 1.0
  tf_tolerance: 0.1
  without_odom: true

