delivery:
  bottom:
    pts:
      - x: 0.9
        y: 0.5
      - x: 1.2
        y: 0.3
      - x: 1.2
        y: -0.3
      - x: 0.9
        y: -0.5
      - x: -0.4
        y: -0.5
      - x: -0.6
        y: -0.3
      - x: -0.6
        y: 0.3
      - x: -0.4
        y: 0.5

  top:
    pts:
      - x: 1.0
        y: 0.55
      - x: 1.3
        y: 0.35
      - x: 1.3
        y: -0.35
      - x: 1.0
        y: -0.55
      - x: 0.5
        y: -0.55
      - x: 0.5
        y: -0.25
      - x: -0.25
        y: -0.25
      - x: -0.25
        y: -0.55
      - x: -0.4
        y: -0.55
      - x: -0.6
        y: -0.4
      - x: -0.6
        y: 0.4
      - x: -0.4
        y: 0.55
      - x: -0.25
        y: 0.55
      - x: -0.25
        y: 0.25
      - x: 0.5
        y: 0.25
      - x: 0.5
        y: 0.55

table_picking:
  pts:
      - x: 0.9
        y: 0.6
      - x: 1.2
        y: 0.4
      - x: 1.2
        y: -0.4
      - x: 0.9
        y: -0.6
      - x: 0.5
        y: -0.6
      - x: 0.5
        y: 0.6

table_dropping:
  pts:
      - x: 0.9
        y: 0.6
      - x: 1.2
        y: 0.4
      - x: 1.2
        y: -0.4
      - x: 0.9
        y: -0.6
      - x: 0.5
        y: -0.6
      - x: 0.5
        y: 0.6

charging:
  pts:
      - x: 0.9
        y: 0.6
      - x: 1.2
        y: 0.4
      - x: 1.2
        y: -0.4
      - x: 0.9
        y: -0.6
      - x: 0.0
        y: -0.6
      - x: -0.2
        y: -0.4
      - x: -0.2
        y: 0.4
      - x: 0.0
        y: 0.6

standby:
  pts:
    - x: 0.9
      y: 0.6
    - x: 1.0
      y: 0.5
    - x: 1.0
      y: -0.5
    - x: 0.9
      y: -0.6
    - x: -0.5
      y: -0.6
    - x: -0.6
      y: -0.5
    - x: -0.6
      y: 0.5
    - x: -0.5
      y: 0.6

camera:
  pts:
    - x: 0.7
      y: 0.3
    - x: 0.7
      y: -0.3
    - x: 1.5
      y: -0.5
    - x: 1.5
      y: 0.5
