pose:
  # HOME
  - x: 0.35
    y: 2.35
    z: -0.1
    qx: 0.0
    qy: 0.0
    qz: -0.726
    qw: 0.687
  # Restore LOC 1
  - x: 4.6
    y: 10.2
    z: -0.4
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0
  # Restore LOC 2
  - x: 29.05
    y: 21.8
    z: -0.3
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0
