velocity_smoother:
# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

  # Mandatory parameters
  speed_lim_v: 1.0
  speed_lim_w: 1.0

  accel_lim_v: 8.0 #5.0
  accel_lim_w: 4.0 #2.0

  # Optional parameters
  frequency: 50.0
  decel_factor: 25.0 #40.0 #deceleration/acceleration ratio

  # Robot velocity feedback type:
  #  0 - none
  #  1 - odometry
  #  2 - end robot commands
  robot_feedback: 1

