delivery:
  bottom:
    pts:
      - x: 0.9
        y: 0.45
      - x: 1.1
        y: 0.4
      - x: 1.1
        y: -0.4
      - x: 0.9
        y: -0.45
      - x: -0.4
        y: -0.45
      - x: -0.7
        y: -0.4
      - x: -0.7
        y: 0.4
      - x: -0.4
        y: 0.45

  top:
    pts:
      - x: 0.9
        y: 0.45
      - x: 1.1
        y: 0.4
      - x: 1.1
        y: -0.4
      - x: 0.9
        y: -0.45
      - x: 0.6
        y: -0.45
      - x: 0.6
        y: -0.25
      - x: -0.4
        y: -0.25
      - x: -0.4
        y: -0.5
      - x: -0.5
        y: -0.5
      - x: -0.7
        y: -0.4
      - x: -0.7
        y: 0.4
      - x: -0.5
        y: 0.5
      - x: -0.4
        y: 0.5
      - x: -0.4
        y: 0.25
      - x: 0.6
        y: 0.25
      - x: 0.6
        y: 0.45

table_picking:
  pts:
      - x: 0.75
        y: 0.55
      - x: 1.0
        y: 0.45
      - x: 1.0
        y: -0.45
      - x: 0.75
        y: -0.55
      - x: 0.5
        y: -0.55
      - x: 0.5
        y: 0.55

table_dropping:
  pts:
      - x: 0.9
        y: 0.6
      - x: 1.1
        y: 0.5
      - x: 1.1
        y: -0.5
      - x: 0.9
        y: -0.6
      - x: 0.5
        y: -0.6
      - x: 0.5
        y: 0.6

charging:
  pts:
      - x: 0.85
        y: 0.6
      - x: 1.05
        y: 0.4
      - x: 1.05
        y: -0.4
      - x: 0.85
        y: -0.6
      - x: 0.0
        y: -0.6
      - x: -0.2
        y: -0.5
      - x: -0.2
        y: 0.5
      - x: 0.0
        y: 0.6

standby:
  pts:
    - x: 0.9
      y: 0.6
    - x: 1.0
      y: 0.5
    - x: 1.0
      y: -0.5
    - x: 0.9
      y: -0.6
    - x: -0.5
      y: -0.6
    - x: -0.6
      y: -0.5
    - x: -0.6
      y: 0.5
    - x: -0.5
      y: 0.6

camera:
  pts:
    - x: 0.7
      y: 0.3
    - x: 0.7
      y: -0.3
    - x: 1.6
      y: -0.5
    - x: 1.6
      y: 0.5
