delivery:
  pts:
    - x: 1.3
      y: 0.7
    - x: 1.3
      y: -0.7
    - x: -0.6
      y: -0.7
    - x: -0.6
      y: 0.7

table_picking:
  pts:
    - x: 0.4
      y: 0.3
    - x: 0.4
      y: -0.3
    - x: -0.0
      y: -0.0
    - x: -0.0
      y: 0.0

table_dropping:
  pts:
    - x: 0.1
      y: 0.1
    - x: 0.1
      y: -0.1
    - x: -0.1
      y: -0.1
    - x: -0.1
      y: 0.1

charging:
  pts:
    - x: 1.0
      y: 0.5
    - x: 1.0
      y: -0.5
    - x: -0.0
      y: -0.5
    - x: -0.0
      y: 0.5

standby:
  pts:
    - x: 1.0
      y: 0.5
    - x: 1.0
      y: -0.5
    - x: -0.0
      y: -0.5
    - x: -0.0
      y: 0.5

inner:
  pts:
    - x: 0.4
      y: 0.5
    - x: 0.4
      y: -0.5
    - x: -0.1
      y: -0.5
    - x: -0.1
      y: 0.5
