topics:
  /laser_3d/points
  /laser_2d/front_left/scan
  /laser_2d/front_left/scan_filter
  /laser_2d/rear_right/scan
  /laser_2d/rear_right/scan_filter
  /laser_2d/merged_cloud
  /filtered_pc2
  /os1_cloud_node/imu
  /imu/data_raw
  /imu/mag
  /camera/color/camera_info
  /camera/color/image_raw
  /camera/depth/camera_info
  /camera/depth/color/points
  /camera/depth/image_rect_raw
  /camera/extrinsics/depth_to_color
  /camera/pointcloud/parameter_descriptions
  /camera/pointcloud/parameter_updates
  /camera/realsense2_camera_manager/bond
  /camera/rgb_camera/parameter_descriptions
  /camera/rgb_camera/parameter_updates
  /camera/stereo_module/parameter_descriptions
  /camera/stereo_module/parameter_updates
  /battery/voltage
  /battery/percent
  /fsm_node/state
  /joy
  /detected_region
  /path
  /path_velocity
  /speed_path/viz
  /table/viz/pathPt
  /tf
  /tf_static
  /map
  /map_metadata
  /mcl_3dl/debug_marker
  /mcl_3dl/matched
  /mcl_3dl/particles
  /mcl_3dl/status
  /mcl_3dl/unmatched
  /mcl_3dl/updated_map
  /trajectory_tracker_forward_driving/status
  /trajectory_tracker_forward_driving/tracking
  /trajectory_tracker_reverse_driving/status
  /trajectory_tracker_reverse_driving/tracking
  /cmd_vel
  /twist_cmd_mux/active
  /twist_cmd_mux/input/autonomous
  /twist_cmd_mux/input/default
  /twist_cmd_mux/input/safety/obstacle
  /twist_cmd_mux/input/stop
  /twist_cmd_mux/input/teleop
  /twist_cmd_mux/input/turn
  /twist_cmd_mux/output
  /twist_cmd_mux/parameter_descriptions
  /twist_cmd_mux/parameter_updates
  /velocity_smoother/parameter_descriptions
  /velocity_smoother/parameter_updates
  /velocity_smoother_nodelet_manager/bond
  /amcl_pose
  /wheel/odom
  /wheel/encoders
  /gyro/odom
  /bumper/status
  /estop/status
  /table/status
  /lifter/status
  /motor/health
  /low_level/status
  /low_level/write
  /lifter/cmd
  /led/cmd
  /web/all_status
  /web/mission
  /health/error
